// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhZFJWY9KD2dU9RTiRYHZ3qul1rFEq4g8',
    appId: '1:830320404723:web:5407013f6c27a52d276f86',
    messagingSenderId: '830320404723',
    projectId: 'coding-diary-90a77',
    authDomain: 'coding-diary-90a77.firebaseapp.com',
    storageBucket: 'coding-diary-90a77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YRagAPdiSLlumLI2cXtY-bfp5IBtEMw',
    appId: '1:830320404723:android:553fae5cec7794d4276f86',
    messagingSenderId: '830320404723',
    projectId: 'coding-diary-90a77',
    storageBucket: 'coding-diary-90a77.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5b78IM6t8Vzi-C_ziEkqtMPXJGDs42M',
    appId: '1:830320404723:ios:402321bf0989549e276f86',
    messagingSenderId: '830320404723',
    projectId: 'coding-diary-90a77',
    storageBucket: 'coding-diary-90a77.firebasestorage.app',
    androidClientId: '830320404723-i2gknase1e3dqnfr0h4u1q0q648mko42.apps.googleusercontent.com',
    iosClientId: '830320404723-063lu00f9kfl8ijpc1smqt7iof3l68ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingDiary',
  );
}
